version: "3.8"
services:
  mysql:
    image: mariadb:10.6.5
    container_name: mariadb-maxair
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3307"
  phpmyadmin:
    depends_on:
      -   mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-maxair
    ports:
      - '8008:80'
    environment:
      PMA_HOST: mysql